version: '3'
services:
  
  #digota:
  #  image: digota/digota:0.1
  #  ports:
  #   - 8080:80
  #  environment:
  #    DIGOTA_ADDRESS: "0.0.0.0:80"
  #    DIGOTA_INSECURE: "TRUE"
  #    DIGOTA_STORAGE_HANDLER: mongodb
  #    DIGOTA_STORAGE_ADDRESS: mongodb:27017
  #    DIGOTA_LOCKER_HANDLER: zookeeper
  #    DIGOTA_LOCKER_ADDRESS: zookeeper:2181
  #  depends_on:
  #    zookeeper:
  #      condition: service_healthy
  #    mongodb:
  #      condition: service_started

  zookeeper:
    image: bitnami/zookeeper:3.9
    restart: unless-stopped
    ports:
      - 2181:2181
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    healthcheck:
      test: ["CMD", "zkServer.sh", "status"]
      interval: 5s
      timeout: 3s
      retries: 5

  mongodb:
    image: mongo:4.4
    restart: unless-stopped
    ports:
      - "27017:27017"

  debug:
    image: nicolaka/netshoot
    command: sleep infinity
    depends_on:
      - zookeeper
    network_mode: service:zookeeper

